import localFont from "next/font/local";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const geistSans = localFont( {
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
} );
const geistMono = localFont( {
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
} );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
  return (
    <html lang="en">
      <body
        className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }
      >
        { children }
        <ToastContainer
          position="top-right"
          autoClose={ 4000 }
          hideProgressBar={ false }
          newestOnTop
          closeOnClick
          rtl={ false }
          pauseOnFocusLoss
          draggable
          pauseOnHover
          progressClassName="Toast__progress_bar"
          closeButton={ false }
        />
      </body>
    </html>
  );
}
